# Generated by Django 4.2.2 on 2023-06-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=50)),
                ('tipo_animal', models.CharField(max_length=50)),
                ('idade_pet', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
    ]
